### ISSUE TITLE
Aim of this repo?

### ISSUE THREAD

**Issue by KevinOfNeu** [jiananshi/giraffehire#1]
what is the usage of giraffehire [Smirk]

**Comment by jiananshi** [comment]
<img width="415" alt="2018-04-19 9 51 32" src="https://user-images.githubusercontent.com/8141958/38995643-f4b33d12-441b-11e8-8280-12d034310ec2.png">

Some popup injected into blog site help hiring people, currently working on minimum bundle code size, will provide a short intro once finished 😝
